### PR TITLE
Allow 'postmessage' callbackURL

### PR DESCRIPTION
**Pull request by tamird**
@jaredhanson this should allow people to use the google-supplied javascript to render the g+ button. 

Fixes jaredhanson/passport-google-oauth#21

cc @praneshkmr @bhvaleri

[Review on Reviewable](https://reviewable.io/reviews/jaredhanson/passport-oauth2/12)

### CODE REVIEW

**Comment by tamird** [comment]
@jaredhanson can you please take a look?

**Comment by tamird** [comment]
@jaredhanson can you take a look?

**Comment by jaredhanson** [comment]
As I understand things, `postmessage` is used for client-side authentication, for example in a SPA.  How does this relate to authentication that is handled server-side, using the `code` flow as done by this strategy?

**Comment by tamird** [comment]
> As I understand things, postmessage is used for client-side authentication, for example in a SPA.
Correct.
> How does this relate to authentication that is handled server-side, using the code flow as done by this strategy?
The server does its thing and then passes back the redirect URL, but the client is expecting `"postmessage"`, not `"http://hostname.com/postmessage"`. That's why it's necessary to avoid the "massaging" code in that case.

Note that I wrote this code 2 years ago, so please pardon inaccuracies in this comment. The important part is that the "postmessage" callback URL most remain unmolested.

**Comment by jaredhanson** [comment]
If the server does a redirect to initiate authentication, how is the client-side JS loaded and waiting to receive a response via `postmessage`?

**Comment by tamird** [comment]
Sorry, I can't remember the details. If you attempt to follow https://developers.google.com/identity/sign-in/web/sign-in#add_a_google_sign-in_button with a server that uses this library, you'll quickly run into this issue.

**Comment by tamird** [comment]
Oh, google has a first party solution https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/oauth2client.js#L384

**Comment by patrykziem** [comment]
Hello guys, the idea of putting `'postmessage'` as `redirect_uri` is that google needs to get the very same value that it got from web app while it was asking for the auth code. It won't be trying to use post message API on server. It just needs it to be equal to this value, otherwise it rejects the call. I'm pretty sure it just means them to ignore the redirection.

See [point 7 in related google docs](https://developers.google.com/identity/sign-in/web/server-side-flow)

**Pull request closed without merging**
