### PR TITLE
Add option for redirect override in authenticate call

### PR DESCRIPTION
**Pull request by danielcorin**

### CODE REVIEW

**Comment by jaredhanson** [comment]
Can you describe the use case here?  How would the override operate in a way different than the standard redirect?

**Comment by danielcorin** [comment]
We're seeking to expose the `status` variable configuration which exists in the core passport library [here](https://github.com/jaredhanson/passport/blob/08f57c2e3086955f06f42d9ac7ad466d1f10019c/lib/middleware/authenticate.js#L327) but is no longer exposed in this library. I believe this change would preserve the `passport` library's original behavior described in the comment.

```
Redirect to `url` with optional `status`, defaulting to 302.
```

Our use case is that we'd like to use passport and passport-oauth2 to construct the URL of our external authentication server and return it as a `Location` header, but don't actually want it to instruct the browser to redirect.

**Comment by jaredhanson** [comment]
My suggestion would be to add a `statusCode` option, something like:

```
passport.authenticate({ statusCode: 303});
```

Seems more readable that passing a function that takes the strategy itself as an argument.  And I can't think of any use cases where something other than the status code would be changed on redirect.

**Comment by danielcorin** [comment]
That sounds reasonable to be. Let me author a new PR and I will close this one out once I do. Thanks for the feedback!

**Comment by danielcorin** [comment]
Closing in favor of https://github.com/jaredhanson/passport-oauth2/pull/123

**Pull request closed without merging**
