### PR TITLE
Support PKCE.

### PR DESCRIPTION
**Pull request by sjudson**
This PR adds support for PKCE (https://tools.ietf.org/html/rfc7636), which provides a method for binding an authorization request and token request together independent of the response to the authorization request itself (as the authorization code does). For, should that response be stolen, there is nothing preventing an adversary from successfully executing the token exchange themselves. This is particularly relevant for public clients, but is generally an additional security measure. The PKCE support can be trigged by incorporation of a `pkceMethod` flag during configuration of the strategy, with possible values of

- `plain`
- `S256`

The latter is greatly preferred, and authorization servers supporting PKCE are not required to support the former.

### CODE REVIEW

**Comment by rwky** [comment]
@sjudson if you make a PR against https://github.com/passport-next/passport-oauth2 is will get looked into.

**Comment by adamhathcock** [comment]
This looks good to me.  Why wasn't the pkce branch never finished?

**Comment by sjudson** [comment]
@jaredhanson - After being reminded it was sitting here (thanks @adamhathcock for the comment) I've updated this PR and removed all merge conflicts. 

The build seems to be failing in TravisCI because something about the test infrastructure doesn't like some code in a dependency which is using ES6 patterns. As Node is all ES6 compatible for supported releases I think this should be considered a test issue, and not a PR issue.

**Comment by rwky** [comment]
@sjudson this repo isn't maintained, if you want to create a PR against https://github.com/passport-next/passport-oauth2 we'll take a look.

**Comment by adamhathcock** [comment]
Is that the new “official” set of packages?

**Comment by jaredhanson** [comment]
@adamhathcock - The official package is this one.

**Comment by adamhathcock** [comment]
Thanks @jaredhanson 

What would it take to get this PR merged?  Are there future plans for this package and Passport in general?  I seem to notice your attention might be elsewhere?  Just looking to volunteer a bit as my interests currently align with this project.

**Comment by tanyaYourchuck** [comment]
I'm wondering the same as @adamhathcock , any new updates on this?

**Comment by tanyaYourchuck** [comment]
@adamhathcock @jaredhanson Any chance you'd be willing to drop support for those older node versions to get the pkce support merged in?

**Comment by joshjung** [comment]
Is this going to be finished at any point? If not, should I be switching away from Passport completely sometime soon?

**Comment by jaredhanson** [comment]
I've merged this (with modifications via #108) and published as `passport-oauth2@1.5.0` to npm.

More information: https://medium.com/passportjs/pkce-support-for-oauth-2-0-e3a77013b278

Thanks @sjudson!

**Comment by joshjung** [comment]
Fantastic!

**Pull request merged**
