### PR TITLE
Bump `oauth` from 0.9.x to 0.10.x

### PR DESCRIPTION
**Pull request by Quentin-Danjou**
This is solving issues of `passport-google-oauth2` as stated in issue [#163](https://github.com/jaredhanson/passport-oauth2/issues/163)

### CODE REVIEW

**Comment by ahmet** [comment]
needed this

**Comment by TwistedLogic** [comment]
Can you please merge this and release a new version? `passport-spotify` has issues.

**Comment by Quentin-Danjou** [comment]
@jaredhanson is there anything I can do so we can merge this?

**Comment by fractallian** [comment]
We need this as well 🙏

**Comment by serniebanders** [comment]
Please

**Comment by pablomusumeci** [comment]
Please, can we get this one merged? It would be extremely helpful 🙏

**Comment by cjezinne** [comment]
@jaredhanson can we get this merged?

**Comment by pablomusumeci** [comment]
@cjezinne thanks! Although, relying on an unofficial fork is not a future-proof solution 😢

**Comment by rjenkin** [comment]
For anyone else with this issue, I've found a workaround to force `passport-oauth2` to use `oauth@0.10.0` by adding an override into my project's `package.json`:
```
    "overrides": {
        "oauth": "~0.10.0"
    }
```

When the node_modules were deleted/reinstalled, `passport-oauth2` was using version 0.10.0:
```
$ npm list oauth
server@1.0.0 /Users/.../webserver
└─┬ passport-oauth2@1.6.1
  └── oauth@0.10.0
```

Just keep in mind that this code should be removed if `passport-oauth2` is ever upgraded in future to use a higher version of oauth, e.g 0.11.0 which currently doesn't exist.

**Comment by pedrohma** [comment]
@rjenkin you are the man

**Comment by pedrohma** [comment]
@jaredhanson please merge this PR

**Comment by grigored** [comment]
> For anyone else with this issue, I've found a workaround to force `passport-oauth2` to use `oauth@0.10.0` by adding an override into my project's `package.json`:
> 
> ```
>     "overrides": {
>         "oauth": "~0.10.0"
>     }
> ```
> 
> When the node_modules were deleted/reinstalled, `passport-oauth2` was using version 0.10.0:
> 
> ```
> $ npm list oauth
> server@1.0.0 /Users/.../webserver
> └─┬ passport-oauth2@1.6.1
>   └── oauth@0.10.0
> ```
> 
> Just keep in mind that this code should be removed if `passport-oauth2` is ever upgraded in future to use a higher version of oauth, e.g 0.11.0 which currently doesn't exist.

Thanks a lot for this fix! For `yarn` users, instead of `overrides` you should use `resolutions`. Also, if you are using yarn workspaces make sure to put this in the **root** `package.json`

**Comment by jaredhanson** [comment]
Merged and published as `passport-oauth2@1.8.0`. Thanks!

**Pull request merged**
