### PR TITLE
Add option to parse user profile from id_token

### PR DESCRIPTION
**Pull request by Nigh7Sh4de**
I was implementing this to create a new strategy for Twitch authentication on the new API. The response on authentication includes an `id_token` param (which is a [JWT](https://jwt.io/)) from which the user's profile may be parsed. So I added an option `parseIdToken` for `Strategy` which decides whether the overloadable `userProfile` receives an access token or an id token.

### CODE REVIEW

**Comment by Nigh7Sh4de** [comment]
Oops forgot the unit tests... pushed.

**Comment by rwky** [comment]
@Nigh7Sh4de if you make a PR against https://github.com/passport-next/passport-oauth2 is will get looked into.

**Comment by Nigh7Sh4de** [comment]
https://github.com/passport-next/passport-oauth2/pull/8

**Comment by Nigh7Sh4de** [comment]
Moved to correct repo. Sorry for the hastle!

**Pull request closed without merging**
