### PR TITLE
handling of refresh_token grant type added

### PR DESCRIPTION
**Pull request by VulcanianRuby**
This will help the user of the strategy to use it for getting access_token by "refresh_token" grant_type request.

### CODE REVIEW

**Comment by jaredhanson** [comment]
Refresh tokens are used out-of-band of the user authentication/authorization request.  This functionality isn't necessary in `passport-oauth2`.

**Comment by VulcanianRuby** [comment]
Hi,
 I'm build an authorization proxy server which unites authorization to several OAuth servers, In this case the ability to proxy also   refresh tokens handling is part of the full OAuth2 package.

 
 

Date: Mon, 8 Feb 2016 14:24:09 -0800

**Comment by jaredhanson** [comment]
That's fine. The functionality does not belong in this strategy.

**Comment by joh-klein** [comment]
Use this https://www.npmjs.com/package/passport-oauth2-refresh like this:
`refresh.requestNewAccessToken('oauth2', 'refresh_token', function(err, accessToken, refreshToken) {});`

**Pull request closed without merging**
